apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: develop
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  type: LoadBalancer